Create plugin for payments-example
reactioncommerce/plugin-payments-example pull request #1
Opened 2020-03-04 18:16 UTC by trojanh

Resolves https://github.com/reactioncommerce/reaction/issues/6129
Impact: **minor**
Type: **refactor**

## Issue
Convert the payments-example plugin. This includes moving all related files into a new repository, releasing that repo as an npm package, and then updating this repo, reaction, to use the npm version of the plugin.

Part of this epic to move all plugins into their own repositories and release as npm packages.

2020-03-09 22:58 UTC, kieckhafer requested changes
A couple small changes just looking at the code. Will test installed next.

2020-03-09 22:58 UTC, kieckhafer commented on package.json
> +  "version": "1.0.0",
Version should be changed to `0.0.0-development", `semantic-release` will take care of bumping the version numbers, it doesn't need to be set here.

2020-03-09 22:58 UTC, kieckhafer commented on src/index.js
> +    version: app.context.appVersion,
This version should be imported from `package.json`.

Change this line to `version: pkg.version`, and then `import pkg from "../package.json";`

2020-03-10 05:58 UTC, kieckhafer commented
@trojanh looks great overall, a couple small comments, but works as expected aside from those. Will merge once those comments addressed.

2020-03-10 13:37 UTC, trojanh commented
great, thanks for reviewing @kieckhafer , this new way of importing plugins from the package is really cool and keeps the main API clean. 

If I get a chance I'll move more such plugins to npm packages.

2020-03-10 13:38 UTC, trojanh commented
I have updated the code as per your suggestion.

2020-03-10 16:04 UTC, kieckhafer approved these changes

2020-03-10 16:04 UTC, merged

2020-03-10 16:15 UTC, rc-publisher commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@reactioncommerce/plugin-payments-example/v/1.0.0)
- [GitHub release](https://github.com/reactioncommerce/plugin-payments-example/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: